[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_program_1 = "BiPhBki2N2m9EtALKMPFjs2KPuwJ2vdU7wMUHkkc3CAd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/alwin-helor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-program-1.ts"
